name: mission_launch
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  audioplayers: ^6.1.0
  bloc: ^8.1.4
  equatable: ^2.0.5
  flame: ^1.20.0
  flame_audio: ^2.10.4
  flame_behaviors: ^1.2.0
  flame_bloc: ^1.12.12
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  nes_ui: ^0.24.1

dev_dependencies:
  bloc_test: ^9.1.7

  build_runner:
  flame_test: ^1.19.1
  flutter_gen_runner:
  flutter_test:
    sdk: flutter
  mockingjay: ^0.6.0
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/audio/
    - assets/images/
    - assets/licenses/poppins/
